stages:
  preprocess:
    cmd: python src/data/data_formatting.py
    deps:
    - data/raw/cell2celltrain.csv
    - src/data/data_utils.py
    - src/data/data_formatting.py
    outs:
    - data/processed/train_index.pkl
    - data/processed/test_index.pkl
    - encoders/OneHotEncoder.pkl
    - encoders/SimpleImputer.pkl
    - encoders/TargetEncoder.pkl
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  eda:
    cmd: python src/data/data_exploration.py
    deps:
    - src/data/data_exploration.py
    - src/data/data_utils.py
    - data/processed/X_train.csv
    - data/processed/y_train.csv
    outs:
    - data/processed/highly_correlated_feature_pairs.pkl
    plots:
    - images/eda:
        type: image
  feature_engineering:
    cmd: python src/data/feature_engineering.py
    deps:
    - src/data/feature_engineering.py
    - src/data/data_utils.py
    - data/processed/X_train.csv
    - data/processed/X_test.csv
    outs:
    - encoders/MinMaxScaler.pkl
    - encoders/PCA_transformer_scaled.pkl
    - encoders/PCA_transformer_smote.pkl
    - data/processed/scaled/X_train_scaled.csv
    - data/processed/scaled/X_test_scaled.csv
    - data/processed/scaled/X_train_scaled_pca.csv
    - data/processed/scaled/X_test_scaled_pca.csv
    - data/processed/smote/X_train_smote.csv
    - data/processed/smote/y_train_smote.csv
    - data/processed/smote/X_train_smote_pca.csv
    - data/processed/smote/X_test_smote_pca.csv
  rfecv_feature_reduction:
    foreach:
      - model: log
        sample: scaled
      - model: rf
        sample: scaled
      - model: xgb
        sample: scaled
      - model: log
        sample: smote
      - model: rf
        sample: smote
      - model: xgb
        sample: smote
    do:
      cmd: python src/data/rfecv_feature_reduction.py --model ${item.model} --sample ${item.sample}
      deps:
      - src/data/rfecv_feature_reduction.py
      - src/data/data_utils.py
      - data/processed/scaled/X_train_scaled.csv
      - data/processed/y_train.csv
      - data/processed/smote/X_train_smote.csv
      - data/processed/smote/y_train_smote.csv
      outs:
      - data/processed/${item.sample}/RFECV_features_${item.model}.pkl
  pso_feature_reduction:
    foreach:
      - model: log
        sample: scaled
      - model: rf
        sample: scaled
      - model: xgb
        sample: scaled
      - model: log
        sample: smote
      - model: rf
        sample: smote
      - model: xgb
        sample: smote
    do:
      cmd: python src/data/pso_feature_reduction.py --model ${item.model} --sample ${item.sample}
      deps:
      - src/data/pso_feature_reduction.py
      - src/data/data_utils.py
      - src/data/pso_utils.py
      - data/processed/pso_options.pkl
      - data/processed/scaled/X_train_scaled.csv
      - data/processed/y_train.csv
      - data/processed/smote/X_train_smote.csv
      - data/processed/smote/y_train_smote.csv
      outs:
      - data/processed/${item.sample}/pso_feature_set_${item.model}.pkl
  baseline_model_training:
    foreach:
      - model: log
        sample: scaled
      - model: rf
        sample: scaled
      - model: xgb
        sample: scaled
      - model: log
        sample: smote
      - model: rf
        sample: smote
      - model: xgb
        sample: smote
    do:
      cmd: python src/models/train_models.py --model ${item.model} --sample ${item.sample} --strategy baseline
      deps:
      - src/models/train_models.py
      - src/models/general_utils.py
      - src/models/training_utils.py
      - data/processed/scaled/X_train_scaled.csv
      - data/processed/scaled/X_test_scaled.csv
      - data/processed/smote/X_train_smote.csv
      - data/processed/smote/y_train_smote.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      outs:
      - models/${item.sample}/baseline_${item.model}_model.pkl
      - models/${item.sample}/baseline_${item.model}_params.json
      - models/${item.sample}/baseline_feature_importances_${item.model}.csv      
      metrics:
      - metrics/${item.sample}/baseline_scores_${item.model}.json
  rfecv_model_training:
    foreach:
      - model: log
        sample: scaled
      - model: rf
        sample: scaled
      - model: xgb
        sample: scaled
      - model: log
        sample: smote
      - model: rf
        sample: smote
      - model: xgb
        sample: smote
    do:
      cmd: python src/models/train_models.py --model ${item.model} --sample ${item.sample} --strategy rfecv
      deps:
      - src/models/train_models.py
      - src/models/general_utils.py
      - src/models/training_utils.py
      - data/processed/scaled/X_train_scaled.csv
      - data/processed/scaled/X_test_scaled.csv
      - data/processed/smote/X_train_smote.csv
      - data/processed/smote/y_train_smote.csv
      - data/processed/${item.sample}/RFECV_features_${item.model}.pkl
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      outs:
      - models/${item.sample}/rfecv_${item.model}_model.pkl
      - models/${item.sample}/rfecv_${item.model}_params.json
      - models/${item.sample}/rfecv_feature_importances_${item.model}.csv      
      metrics:
      - metrics/${item.sample}/rfecv_scores_${item.model}.json
  pca_model_training:
    foreach:
      - model: log
        sample: scaled
      - model: rf
        sample: scaled
      - model: xgb
        sample: scaled
      - model: log
        sample: smote
      - model: rf
        sample: smote
      - model: xgb
        sample: smote
    do:
      cmd: python src/models/train_models.py --model ${item.model} --sample ${item.sample} --strategy pca
      deps:
      - src/models/train_models.py
      - src/models/general_utils.py
      - src/models/training_utils.py
      - data/processed/scaled/X_train_scaled_pca.csv
      - data/processed/scaled/X_test_scaled_pca.csv
      - data/processed/smote/X_train_smote_pca.csv
      - data/processed/smote/y_train_smote.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      outs:
      - models/${item.sample}/pca_${item.model}_model.pkl
      - models/${item.sample}/pca_${item.model}_params.json
      - models/${item.sample}/pca_feature_importances_${item.model}.csv      
      metrics:
      - metrics/${item.sample}/pca_scores_${item.model}.json
  pso_model_training:
    foreach:
      - model: log
        sample: scaled
      - model: rf
        sample: scaled
      - model: xgb
        sample: scaled
      - model: log
        sample: smote
      - model: rf
        sample: smote
      - model: xgb
        sample: smote
    do:
      cmd: python src/models/train_pso.py --model ${item.model} --sample ${item.sample}
      deps:
      - src/models/train_pso.py
      - src/models/general_utils.py
      - src/models/pso_training_utils.py
      - data/processed/scaled/X_train_scaled.csv
      - data/processed/scaled/X_test_scaled.csv
      - data/processed/smote/X_train_smote.csv
      - data/processed/smote/y_train_smote.csv
      - data/processed/${item.sample}/pso_feature_set_${item.model}.pkl
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      outs:
      - models/${item.sample}/pso_${item.model}_model.pkl
      - models/${item.sample}/pso_${item.model}_params.json
      - models/${item.sample}/pso_feature_importances_${item.model}.csv      
      metrics:
      - metrics/${item.sample}/pso_scores_${item.model}.json
      - metrics/${item.sample}/pso_grid_scores_${item.model}.json
  model_visualization:
    cmd: python src/models/visualize_results.py
    deps:
    - src/models/visualize_results.py
    - src/models/vis_utils.py
    - metrics/scaled/baseline_scores_log.json
    - metrics/scaled/baseline_scores_rf.json
    - metrics/scaled/baseline_scores_xgb.json
    - metrics/scaled/pca_scores_log.json
    - metrics/scaled/pca_scores_rf.json
    - metrics/scaled/pca_scores_xgb.json
    - metrics/scaled/pso_scores_log.json
    - metrics/scaled/pso_scores_rf.json
    - metrics/scaled/pso_scores_xgb.json
    - metrics/scaled/rfecv_scores_log.json
    - metrics/scaled/rfecv_scores_rf.json
    - metrics/scaled/rfecv_scores_xgb.json
    - metrics/smote/baseline_scores_log.json
    - metrics/smote/baseline_scores_rf.json
    - metrics/smote/baseline_scores_xgb.json
    - metrics/smote/pca_scores_log.json
    - metrics/smote/pca_scores_rf.json
    - metrics/smote/pca_scores_xgb.json
    - metrics/smote/pso_scores_log.json
    - metrics/smote/pso_scores_rf.json
    - metrics/smote/pso_scores_xgb.json
    - metrics/smote/rfecv_scores_log.json
    - metrics/smote/rfecv_scores_rf.json
    - metrics/smote/rfecv_scores_xgb.json
    plots:
    - images/model_results.png:
        type: image